version: "3"

services: 
  discovery:
    build: ./ms-discovery
    ports: 
      - '8888:8888'
  category:
    build: ./ms-category
    ports: 
      - '8081:8081'
    depends_on:
      - discovery
  account:
    build: ./ms-account
    ports: 
      - '8082:8082'
    depends_on:
      - discovery